
source 'https://github.com/LiBiYong/SpecsLibrary.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'
target 'CTMediatorTarget_Example' do
  pod 'CTMediatorTarget', :path => '../'
  
end
